### ISSUE TITLE
Changing the About section

### ISSUE THREAD

**Issue by metoinside** [ExternalTeam/ForthYouthSummit_KONYA#5]
Please see below image to understand it better

![screen shot 2016-09-08 at 23 57 58](https://cloud.githubusercontent.com/assets/5622253/18366716/81485b8e-7620-11e6-8d2b-8d9ebf004876.png)

**Comment by metoinside** [comment]
"Three days of inspiration still" appears

**Comment by Permitivite** [comment]
Okey 😊
