### ISSUE TITLE
Second Slider Needs Update

### ISSUE THREAD

**Issue by metoinside** [ExternalTeam/ForthYouthSummit_KONYA#7]
On the second slider it says: Eventify 2014 and on the below line: 23–25Sep2013New York
Which needs to replace with the theme of the conference: "Sürdürülebilir Kalkınma Hedefleri Yolunda Gençlik ve STK’lar"

**Comment by Permitivite** [comment]
I don't know what to write instead of "Get Ticket". Do you have any idea?
